USE [LivrariaDaCidadeDB]
GO

/****** Object:  Table [dbo].[LIVRO]    Script Date: 06/09/2017 18:19:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LIVRO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_EDITORA] [int] NOT NULL,
	[NOME] [varchar](150) NOT NULL,
	[VALOR] [float] NOT NULL,
	[SINOPSE] [varchar](2000) NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
 CONSTRAINT [PK_LIVRO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[LIVRO]  WITH CHECK ADD  CONSTRAINT [FK_LIVRO_EDITORA] FOREIGN KEY([ID_EDITORA])
REFERENCES [dbo].[EDITORA] ([ID])
GO

ALTER TABLE [dbo].[LIVRO] CHECK CONSTRAINT [FK_LIVRO_EDITORA]
GO

