USE [LivrariaDaCidadeDB]
GO

/****** Object:  Table [dbo].[LIVRO_AUTOR]    Script Date: 06/09/2017 18:19:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LIVRO_AUTOR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_AUTOR] [int] NOT NULL,
	[ID_LIVRO] [int] NOT NULL,
 CONSTRAINT [PK_LIVRO_AUTOR] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[LIVRO_AUTOR]  WITH CHECK ADD  CONSTRAINT [FK_LIVRO_AUTOR_AUTOR] FOREIGN KEY([ID_AUTOR])
REFERENCES [dbo].[AUTOR] ([ID])
GO

ALTER TABLE [dbo].[LIVRO_AUTOR] CHECK CONSTRAINT [FK_LIVRO_AUTOR_AUTOR]
GO

ALTER TABLE [dbo].[LIVRO_AUTOR]  WITH CHECK ADD  CONSTRAINT [FK_LIVRO_AUTOR_LIVRO] FOREIGN KEY([ID_LIVRO])
REFERENCES [dbo].[LIVRO] ([ID])
GO

ALTER TABLE [dbo].[LIVRO_AUTOR] CHECK CONSTRAINT [FK_LIVRO_AUTOR_LIVRO]
GO

